# Generated by Django 3.2.8 on 2021-10-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='atvidade',
            new_name='atividade',
        ),
    ]
