# Generated by Django 3.2.8 on 2021-10-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='updated_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
