# Generated by Django 3.2.8 on 2021-10-18 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_institution_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Cidade_id_cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Estado_id_estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estado'),
        ),
    ]
