# Generated by Django 3.2.8 on 2021-10-18 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211018_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('horario', models.TimeField(auto_now=True)),
                ('Instituicoes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.institution')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
