# Generated by Django 3.2.8 on 2021-10-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_doacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doacao',
            old_name='Instituicoes_id',
            new_name='Instituicoes',
        ),
        migrations.RenameField(
            model_name='doacao',
            old_name='User_id',
            new_name='User',
        ),
    ]
